# Generated by Django 5.1.5 on 2025-01-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_contact_options_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'managed': True, 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True, 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_convers_3ebb41_idx',
            old_name='conversatio_convers_4b968d_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_sender__6ae55a_idx',
            old_name='conversatio_sender__ed16aa_idx',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='conversations',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
