# Generated by Django 5.1.5 on 2025-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_alter_contact_options_alter_conversation_options_and_more'),
        ('users', '0005_alter_user_options_alter_userstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contacts',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sorted_user_ids',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('user1__lt', models.F('user2'))), fields=('user1', 'user2'), name='unique_contacts'),
        ),
    ]
