# Generated by Django 5.1.5 on 2025-01-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_remove_contact_unique_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='messages_sender__6ae55a_idx',
        ),
    ]
