version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: communication_app_frontend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: "npm start"
