services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: "npm start"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
