services:
  database:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    image: backend
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: "npm start"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data:
