# Generated by Django 5.1.5 on 2025-01-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name': 'User status', 'verbose_name_plural': 'Users status'},
        ),
    ]
