# Generated by Django 5.1.5 on 2025-01-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'managed': True, 'verbose_name': 'User status', 'verbose_name_plural': 'Users status'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userstatus',
            table='user_status',
        ),
    ]
