# Generated by Django 5.1.5 on 2025-01-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_alter_userstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userstatus',
            table='users_status',
        ),
    ]
